name: Add Review Checklist Comment

on:
  pull_request:
    types: [opened]

jobs:
  add-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Post Review Checklist Comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
          -d @- <<EOF
          {
            "body": "**Pull Request Review Checklist**\n\n
            ### Checklist for Reviewers:\n
            - [ ] Code follows project style and naming conventions.\n
            - [ ] Code is well-tested, and functionality is as expected.\n
            - [ ] Documentation and comments are clear and complete.\n
            - [ ] No known security vulnerabilities are introduced.\n
            - [ ] Performance impact has been considered.\n
            \nPlease review the above criteria before approving."
          }
          EOF
