name: T2Module04 - UI Unit test.

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Qt 6.5.0
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.5.0'
          host: 'linux'
          modules: 'qtbase'

      - name: QT Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxcb-xinerama0 libxcb-xinput0 libxkbcommon-x11-0 libxcb-xfixes0-dev \
                                  libxcb-util1 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 \
                                  libxcb-render-util0 libxcb-randr0 libxcb-xkb1 libxkbcommon-dev \
                                  libx11-xcb1 xvfb libxcb-cursor0

      - name: Start Xvfb - Virtual Display
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x16 &
        shell: bash

      - name: CMake Compilation
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_PREFIX_PATH=/home/runner/work/Team02-Module04/Qt/6.5.0/gcc_64 ..
          cmake --build .
        shell: bash
        continue-on-error: false

      - name: Add Permissions to Executables
        run: |
          chmod +x build/*
          echo "Permissions set for test executables in build/"

      - name: USER Interface Unit Tests
        env:
          DISPLAY: ":99"
          QT_DEBUG_PLUGINS: "1"
        run: |
          cd build/
          echo "Running unit UI tests with detailed info"
         # ./run_ui_tests || { echo "UI tests failed"; exit 1; }
        shell: bash
